# Configuration for Azure test cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../apps/eye/base

namespace: "slot1"

replicas:
- name: nginx-deployment
  count: 2
